namespace LeezenPass.Api.Domain.Bikes;

public class BikePhoto
{
  private BikePhoto() { }

  /// <param name="id">Generated by the caller (Guid.CreateVersion7()) because the storage path contains it.</param>
  /// <param name="bikeId">Owning bike.</param>
  /// <param name="kind">What the photo shows.</param>
  /// <param name="path">Storage key of the full-size image.</param>
  /// <param name="createdAt">Upload time.</param>
  public BikePhoto(Guid id, Guid bikeId, PhotoKind kind, string path, DateTimeOffset createdAt)
  {
    Id = id;
    BikeId = bikeId;
    Kind = kind;
    Path = path;
    CreatedAt = createdAt;
  }

  public Guid Id { get; private set; }
  public Guid BikeId { get; private set; }
  public PhotoKind Kind { get; private set; }

  /// <summary>Storage key (see IFileStorage), not a URL.</summary>
  public string Path { get; private set; } = string.Empty;

  public DateTimeOffset CreatedAt { get; private set; }
}
