<Project>
  <ItemGroup>
    <!-- Web -->
    <PackageVersion Include="FastEndpoints" Version="8.3.0" />
    <PackageVersion Include="FastEndpoints.Swagger" Version="8.3.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.9" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.12" />
    <!-- Data -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="10.0.3" />
    <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
    <!-- Infrastructure -->
    <PackageVersion Include="MailKit" Version="4.18.0" />
    <PackageVersion Include="QuestPDF" Version="2026.9.0" />
    <PackageVersion Include="SkiaSharp" Version="4.152.1" />
    <!-- Analyzers -->
    <PackageVersion Include="NsDepCop" Version="3.1.0" />
    <!-- Tests -->
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
